version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10
  maven: circleci/maven@0.0.12

workflows:
  test-and-deploy:
    jobs:
      - maven/test # checkout, build, test, and upload test results
      - heroku/deploy-via-git:
        filters:
          branches:
            only:
              - master
        requires:
            - maven/test
 